### ISSUE TITLE
libsassnet.x64 still on version 3.2.5.1 in NuGet

### ISSUE THREAD

**Issue by billpull** [sass/libsass-net#51]
The current version of the x64 binding of this project is still on v3.2.5.1 versus the core project being at v3.3.7.

I am currently looking to update my project in order to fix this encoding issue https://github.com/sass/libsass-net/issues/24

**Comment by mudnug** [comment]
I would like to see this update as well

**Comment by darrenkopp** [comment]
The x64 packages are no longer necessary and I just haven't unpublished them all (annoying with nuget) yet. You should migrate to using the core projects as they support both x86 and x64.
